### ISSUE TITLE
[FIX] Jusohn님이 찾은 수많은 ERROR

### ISSUE THREAD

**Issue by minseok128** [minseok128/MINISHELL_MERGE#25]
## Summary 
 1월 24일에 minishell 권위자 Jusohn님이 찾은 수많은 ERROR를 명세하고 고칠 것을 기대합니다.
  
## Description 
1. newline과 관련된 것으로 추정되는 leaks 발생
> ```bash
> minishell $ $?|
> minishell: syntax error near unexpected token `newline'
> minishell $
> minishell $ exit
> Process:         minishell [45043]
> Path:            /Volumes/VOLUME/*/minishell
> Load Address:    0x108c91000
> Identifier:      minishell
> Version:         ???
> Code Type:       X86-64
> Parent Process:  zsh [21692]
> 
> Date/Time:       2024-01-23 21:12:48.378 +0900
> Launch Time:     2024-01-23 21:12:39.299 +0900
> OS Version:      Mac OS X 10.15.7 (19H15)
> Report Version:  7
> Analysis Tool:   /Applications/Xcode.app/Contents/Developer/usr/bin/leaks
> Analysis Tool Version:  Xcode 12.3 (12C33)
> 
> Physical footprint:         780K
> Physical footprint (peak):  780K
> ----
> 
> leaks Report Version: 3.0
> Process 45043: 378 nodes malloced for 359 KB
> Process 45043: 2 leaks for 96 total leaked bytes.
> 
> Leak: 0x7fcfba407690  size=48  zone: DefaultMallocZone_0x108ca7000
> Leak: 0x7fcfba4076c0  size=48  zone: DefaultMallocZone_0x108ca7000
> ```
2. 공백과 관련된 Segmentation fault 발생
> ```bash
> minishell $ export a=''
> minishell $ echo $a
> [1]    45138 segmentation fault  ./minishell
> 
> minishell $ unset a
> minishell $ echo $a
> [1]    45229 segmentation fault  ./minishell
> ```
3. word spliting이 제대로 이루어지지 않는 현상
> ```
> minishell $ export a="ho   hi"
> minishell $ ec$a oh
> oh
> ```
4. &&로 연결된 상황에서 발생하는 Segmentation fault 발생
> ```bash
> minishell $ export a=b && echo $a
> [1]    44964 segmentation fault  ./minishell
> ```
5. 조금 손 봤더니 segfault는 발생하지 않는데 정상적인 동작은 하지 않음
> ```bash
> minishell $ export a=b && echo $a
> ```
6. echo 명령어의 파라미터가 존재하지 않을 때 개행이 등장해야하지만, 등장하지 않는 문제
> ```bash
> > minishell $ echo
> > minishell $
> ```
7. export, unset에서 에러 메시지에 `'로 인자를 감싸주지 않고 ''로 감싸 줌
> ```bash
> > minishell: export: '1': not a valid identifier
> > bash: export: `1': not a valid identifier
> ```
8. heredoc 인자가 quote로 감싸져있어도 그대로 들고오는 문제
> ```bash
> minishell $ << "'a'" cat
> 'a'
> a
> "'a'"
> 'a'
> a
> ```

**Comment by minseok128** [comment]
- [ ] : error 1
- [ ] - [ ] : error 1
- [ ] - [ ] : error 1
- [ ] - [ ] : error 1

**Comment by seonjo1** [comment]
- [ ] : error 6
 - [ ] : error 7
 - [ ] : error 8
