### ISSUE TITLE
[FIX] jaehejun님이 주신 테스트케이스 돌리며 나온 문제

### ISSUE THREAD

**Issue by seonjo1** [minseok128/MINISHELL_MERGE#30]
## Summary 
마지막 오류 수정이라 생각하고 열심히 처리하자!
  
## Description 
 1. 파일 open시 파일 mode 를 bash랑 일치시키자
>```c
> // minishell
>minishell $ > a
>minishell $ ls -al a
>-rwxr-xr-x  1 seonjo  2023_seoul  0 Jan 24 18:48 a
>
> // bash
>bash-3.2$ > a
>bash-3.2$ ls -al a
>-rw-r--r--  1 seonjo  2023_seoul  0 Jan 24 18:50 a
>```

2. 실행권한 없는 파일을 경로입력으로 실행할 경우 에러코드가 다르게 뜸
>```c
>// minishell
>minishell $ ./a
>minishell: ./a: Permission denied
>minishell $ echo $?
>13        // unix에서 permission denied는 에러코드가 13임
>
>// bash
>bash-3.2$ ./a
>bash: ./a: Permission denied
>bash-3.2$ echo $?
>126      // bash에서 permission denied는 에러코드가 126임
>```

3. 경로로 입력했을때 중간에 디렉토리가 아닌 파일에 들어가면 Not a directory가 떠야함
>```c
>// minishell
>minishell $ /bin/ls/nofile
>minisehll: /bin/ls/nofile: No such file or directory
>minishell $ echo $?
>127
>// bash
>bash-3.2$ /bin/ls/nofile
>bash: /bin/ls/nofile: Not a directory
>bash-3.2$ echo $?
>126
>```

~~4. syntax error 모음~~
>```c
>// minishell
>//1번
>minishell $ <<<<<<<<
>minishell: syntax error near unexpected token `<<'
>//2번
>minishell $ <>
>minishell: syntax error near unexpected token `>'
>// bash
>// 1번
>bash-3.2$ <<<<<<<<
>bash: syntax error near unexpected token `<<<'
>// 2번
>bash-3.2$ <>
>bash: syntax error near unexpected token `newline'
>```

~~5. heredoc을 파이프로 열고 eof를 여러번 넣으면 >가 1개만 출력되는 현상~~
>```c
>// minishell
>minishell $ << eof > out1 | <<eof > out2 | <<eof > out3
>> minishell $
>// bash
>bash-3.2$ << eof > out1 | <<eof > out2 | <<eof > out3
>> > > bash-3.2$
>```

6. PATH를 삭제하고 명령어 실행시 에러코드가 127이 아닌 2가 나옴
>```c
>// minishell
>minishell $ unset PATH
>minishell $ ls
>minishell: ls: No such file or directory
>minishell $ echo $?
>2
>// bash
>bash-3.2$ unset PATH
>bash-3.2$ ls
>bash: ls: No such file or directory
>bash-3.2$ echo $?
>127
>```

7.  syntax error 발생시 error코드 맞추기
>```c
>// minishell
>minishell $ >>
>minishell: syntax error near unexpected token `newline'
>minishell $ echo $?
>0
>// bash
>bash-3.2$ >>
>bash: syntax error near unexpected token `newline'
>bash-3.2$ echo $?
>258
>```

다행히도 모든 케이스를 넣어보는 동안 leak은 발생하지 않았습니다.

**Comment by seonjo1** [comment]
@minseok128 내일 함께 어디까지 처리할지 생각해 봅시다!

**Comment by minseok128** [comment]
헐 아직도 엄청 많다···!

**Comment by minseok128** [comment]
- 4번의 1번 case는 bash에만 존재하는 `<<<`라는 고유의 기능이 존재하고, 이를 하나의 토큰으로 인식하는 것으로 보입니다. 따라서 해당 기능이 없는 우리는 처리할 필요가 없어보입니다.
- 4번의 2번 case도 마찬가지로 bash에만 존재하는 `<>`라는 고유의 기능에 대한 것입니다. 따라서 처리할 필요가 없는 것 같습니다.
> ```bash
> bash-3.2$ <>
> bash: syntax error near unexpected token `newline'
> bash-3.2$ < >
> bash: syntax error near unexpected token `>'
> ```

**Comment by seonjo1** [comment]
- [ ] : error 1
- [ ] : error 2
- [ ] : error 3
- [ ] : error 4
- [ ] : error 5
- [ ] : error 6
- [ ] : error 7
